from src.hardware.elementary_logic_gates.mux16_gate import mux16_gate
from src.hardware.elementary_logic_gates.dmux_gate import dmux_gate
from src.hardware.sequential_chips.ram16K_chip import Ram16KChipPerformance


class Memory:
    def __init__(self):
        self.mux16_gate = mux16_gate
        self.dmux_gate = dmux_gate
        self.ram16K_chip_a = Ram16KChipPerformance()
        self.ram16K_chip_b = Ram16KChipPerformance()

    def __call__(
        self,
        a0: int,
        a1: int,
        a2: int,
        a3: int,
        a4: int,
        a5: int,
        a6: int,
        a7: int,
        a8: int,
        a9: int,
        a10: int,
        a11: int,
        a12: int,
        a13: int,
        a14: int,
        a15: int,
        load: int,
        add0: int,
        add1: int,
        add2: int,
        add3: int,
        add4: int,
        add5: int,
        add6: int,
        add7: int,
        add8: int,
        add9: int,
        add10: int,
        add11: int,
        add12: int,
        add13: int,
        add14: int,
    ) -> int:
        load_a, load_b = self.dmux_gate(load, add0)
        ram_a = self.ram16K_chip_a(
            a0,
            a1,
            a2,
            a3,
            a4,
            a5,
            a6,
            a7,
            a8,
            a9,
            a10,
            a11,
            a12,
            a13,
            a14,
            a15,
            load_a,
            add1,
            add2,
            add3,
            add4,
            add5,
            add6,
            add7,
            add8,
            add9,
            add10,
            add11,
            add12,
            add13,
            add14,
        )
        ram_b = self.ram16K_chip_b(
            a0,
            a1,
            a2,
            a3,
            a4,
            a5,
            a6,
            a7,
            a8,
            a9,
            a10,
            a11,
            a12,
            a13,
            a14,
            a15,
            load_b,
            add1,
            add2,
            add3,
            add4,
            add5,
            add6,
            add7,
            add8,
            add9,
            add10,
            add11,
            add12,
            add13,
            add14,
        )
        result = self.mux16_gate(*ram_a, *ram_b, add0)
        return result
