from src.hardware.types.bits import Bits16, Bits12, Bit
from src.hardware.elementary_logic_gates.dmux8way_gate import (
    Dmux8WayGate,
    dmux8way_gate,
)
from src.hardware.elementary_logic_gates.mux8way16_gate import (
    Mux8Way16Gate,
    mux8way16_gate,
)
from .ram512_chip import Ram512Chip, Ram512ChipPerformance


class Ram4KChipPerformance:
    def __init__(self):
        self.ram512_a = Ram512ChipPerformance()
        self.ram512_b = Ram512ChipPerformance()
        self.ram512_c = Ram512ChipPerformance()
        self.ram512_d = Ram512ChipPerformance()
        self.ram512_e = Ram512ChipPerformance()
        self.ram512_f = Ram512ChipPerformance()
        self.ram512_g = Ram512ChipPerformance()
        self.ram512_h = Ram512ChipPerformance()
        self.dmux8way_gate = dmux8way_gate
        self.mux8way16_gate = mux8way16_gate

    def __call__(
        self,
        a0: int,
        a1: int,
        a2: int,
        a3: int,
        a4: int,
        a5: int,
        a6: int,
        a7: int,
        a8: int,
        a9: int,
        a10: int,
        a11: int,
        a12: int,
        a13: int,
        a14: int,
        a15: int,
        load: int,
        add0: int,
        add1: int,
        add2: int,
        add3: int,
        add4: int,
        add5: int,
        add6: int,
        add7: int,
        add8: int,
        add9: int,
        add10: int,
        add11: int,
    ) -> int:
        a, b, c, d, e, f, g, h = self.dmux8way_gate(load, add0, add1, add2)
        return self.mux8way16_gate(
            *self.ram512_a(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                a,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_b(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                b,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_c(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                c,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_d(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                d,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_e(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                e,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_f(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                f,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_g(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                g,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            *self.ram512_h(
                a0,
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                h,
                add3,
                add4,
                add5,
                add6,
                add7,
                add8,
                add9,
                add10,
                add11,
            ),
            add0,
            add1,
            add2,
        )


class Ram4KChip:
    def __init__(self):
        self.ram512_a = Ram512Chip()
        self.ram512_b = Ram512Chip()
        self.ram512_c = Ram512Chip()
        self.ram512_d = Ram512Chip()
        self.ram512_e = Ram512Chip()
        self.ram512_f = Ram512Chip()
        self.ram512_g = Ram512Chip()
        self.ram512_h = Ram512Chip()
        self.dmux8way_gate = Dmux8WayGate()
        self.mux8way16_gate = Mux8Way16Gate()

    def __call__(self, in_bits: Bits16, load: Bit, address: Bits12) -> Bits16:
        a, b, c, d, e, f, g, h = self.dmux8way_gate(load, address[:3])
        return self.mux8way16_gate(
            self.ram512_a(in_bits, a, address[3:]),
            self.ram512_b(in_bits, b, address[3:]),
            self.ram512_c(in_bits, c, address[3:]),
            self.ram512_d(in_bits, d, address[3:]),
            self.ram512_e(in_bits, e, address[3:]),
            self.ram512_f(in_bits, f, address[3:]),
            self.ram512_g(in_bits, g, address[3:]),
            self.ram512_h(in_bits, h, address[3:]),
            address[:3],
        )
